# Node Build and Validate on Pull Request
name: PullReq CI

on:
  pull_request:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: 10.x
    - name: npm ci, run validate
      run: |
        # TODO: set env for CI
        touch .env
        npm ci
        npm run validate
      env:
        CI: true
